Repository snap-bug/snap-bug-client, pull requests merged in 2025-03, with the labels that each got.

#27 design: 사이드바 레이아웃 설정
  src/App.jsx
  src/components/DebugPanel.jsx
  src/main.jsx
  src/pages/Debug.jsx
  src/shared/components/Button.jsx
  src/shared/components/Footer.jsx
Labels: design, feat

#28 feat: JSON 목데이터 생성 및 컴포넌트 상태 이력 조회
  src/components/DebugPanel.jsx
  src/components/TimeTravelBox.jsx
  src/public/mock-data/state-history.json
  src/utils/dateUtils.js
Labels: feat

#36 docs: PR 목적과 작업 사유를 명확히 하기 위한 템플릿 개선
  .github/pull_request_template.md
Labels: docs

#40 chore: vite.config.js에서 엔트리파일 자동탐색 제거 (#39)
  vite.config.js
Labels: chore

#41 feat: JSON 데이터 기반 UI 구현 및 개선 (#33)
  index.html
  src/App.jsx
  src/components/DebugPanel.jsx
  src/components/TimeTravelBox.jsx
Labels: feat

#43 fix: next 버튼이 동작하지 않던 이슈 수정 (#42)
  src/components/DebugPanel.jsx
Labels: fix, refactor
